// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkzodyzhxdyztormkfbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrem9keXpoeGR5enRvcm1rZmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODA3OTksImV4cCI6MjA2NTU1Njc5OX0.l9dI4QqKS44ImFK-Y7FrgIUtXMPErYK3fjiGKkadj5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);